org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.4
parchment_mappings_version=2025.03.23

minecraft_version=1.21.4
minecraft_version_range=[1.21.4]

neo_version=21.4.157
neo_version_range=[21.4.0,21.5)
loader_version_range=[1,)

mod_id=langwhitelist
mod_name=Language Whitelist
mod_license=MIT
mod_version=1.3
mod_group_id=com.riabov.langwhitelist
mod_authors=Riabov
mod_description=Filters the Language menu so it only shows the languages you choose.
