modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[mods]]
modId="langwhitelist"
version="${file.jarVersion}"
displayName="Language Whitelist"
authors="Riabov"
description='''
Filters the Language menu so it only shows the languages you choose.
'''
logoFile="icon.png"
logoBlur=false

[[dependencies.langwhitelist]]
modId="forge"
mandatory=true
versionRange="[40.3.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.langwhitelist]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.19)"
ordering="NONE"
side="BOTH"
